language: "hr"
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "EmbeddingIntentClassifier"
  - name: "CRFEntityExtractor"
    features: [["low", "title"], ["bias", "suffix3"], ["upper"]]
    BILOU_flag: true
    max_iterations: 50
    L1_c: 0.1
    L2_c: 0.1

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
