version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 80:5005
    volumes:
      - rasa:/app
    command:
      - run
      - --enable-api
volumes:
  rasa:
    external:
      name: rasa
