version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 8080:5005
    volumes:
      - rasa:/app
    command:
      - run
      - --enable-api
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
volumes:
  rasa:
    external:
      name: rasa